print("TRACK C - MODEL PREDICTION PIPELINE")

import time
import os
import json
import requests
import os
from google import genai
import os
import json
from google.genai import types
import json
import re

from jsonschema import validate
from jsonschema.exceptions import ValidationError

API_KEY = os.environ.get("GOOGLE_API_KEY")
if API_KEY is None:
    raise ValueError(
        "Environment variable 'GOOGLE_API_KEY' not found.\n"
        "Please set your API key before running the script."
    )
client = genai.Client(api_key=API_KEY)
MODEL_NAME = "gemini-2.5-flash"
print("\nAPI Configuration Loaded Successfully.")
print(f"Model : {MODEL_NAME}")

# REUSABLE LLM FUNCTION
def call_llm(system_prompt,
             user_prompt,
             temperature=0.0,
             max_tokens=512):
    cache_file = "llm_cache.json"
    if os.path.exists(cache_file):
        with open(cache_file, "r") as f:
            cache = json.load(f)
    else:
        cache = {}

    key = f"{hash(user_prompt)}_{temperature}"

    if key in cache:
        print("Loaded response from cache.")
        return json.dumps(cache[key], indent=4)
    prompt = f"""
System:
{system_prompt}

User:
{user_prompt}
"""
    try:
        response = client.models.generate_content(
            model=MODEL_NAME,
            contents=prompt,
            config=types.GenerateContentConfig(
                temperature=temperature,
                max_output_tokens=max_tokens))
        text = response.text
        try:
            cache[key] = json.loads(text)
        except:
            cache[key] = text
        with open(cache_file, "w") as f:
            json.dump(cache, f, indent=4)
        return text
    except Exception as e:
        print("\nGemini API Error")
        print(e)
        return None
    
# SIMPLE TEST PROMPT
system_prompt = (
    "You are a helpful assistant."
)
user_prompt = (
    "Reply with only the word: hello"
)
response = call_llm(
    system_prompt=system_prompt,
    user_prompt=user_prompt,
    temperature=0.0,
    max_tokens=10)
print("\nLLM Response:")
print(response)

# BLOCK COMPLETED
print("\nLibraries Imported Successfully")
# SYSTEM PROMPT
SYSTEM_PROMPT = """
You are an expert Machine Learning Prediction Explanation Assistant.
Your job is to explain predictions generated by a binary fraud detection
machine learning model.
You will receive:
1. Feature values
2. Predicted class
3. Prediction probability
Rules:
- Output ONLY valid JSON.
- Do NOT include markdown.
- Do NOT include code blocks.
- Do NOT explain outside the JSON.
- Never invent feature values.
- Never change the prediction.
- Base your explanation only on the supplied information.
- Keep explanations concise and professional.
Return EXACTLY this JSON structure:
{
    "prediction_label": "Fraud or Not Fraud",
    "confidence_level": "low | medium | high",
    "top_reason": "Primary reason",
    "second_reason": "Secondary reason",
    "next_step": "Recommended next action"
}
"""
print("System Prompt Created Successfully")

# USER PROMPT TEMPLATE
USER_PROMPT_TEMPLATE = """
Feature Values
{feature_values}

Predicted Class
{prediction}

Prediction Probability
{probability}

Task
Explain why this prediction was made.
Return ONLY valid JSON using the required schema.
"""
print("User Prompt Template Created Successfully")

# OUTPUT JSON SCHEMA
OUTPUT_SCHEMA = {
    "type": "object",
    "properties": {
        "prediction_label": {
            "type": "string"},
        "confidence_level": {
            "type": "string",
            "enum": ["low","medium","high"]},
        "top_reason": {
            "type": "string"},
        "second_reason": {"type": "string"},
        "next_step": {"type": "string"}},
    "required": ["prediction_label","confidence_level","top_reason","second_reason","next_step"],
    "additionalProperties": False}

# FALLBACK RESPONSE
FALLBACK_RESPONSE = {
    "prediction_label": None,
    "confidence_level": None,
    "top_reason": None,
    "second_reason": None,
    "next_step": None}

# DISPLAY SUMMARY
print("System Prompt Created")
print("User Prompt Template Created")
print("JSON Schema Created")
print("Fallback Dictionary Created")

# JSON VALIDATION FUNCTION
def validate_llm_json(response_text):
    """
    Validate the JSON returned by the LLM.
    Steps:
    1. Remove extra whitespace.
    2. Parse JSON.
    3. Validate against OUTPUT_SCHEMA.
    4. Return fallback dictionary if anything fails.
    """
    # Handle Empty Response
    if response_text is None:
        print("\nNo response received from LLM.")
        return FALLBACK_RESPONSE
    # Remove leading/trailing whitespace
    response_text = response_text.strip()

    # Parse JSON
    try:
        parsed_json = json.loads(response_text)
        print("\nJSON Parsing Successful.")
    except json.JSONDecodeError as error:
        print("\nJSON Parsing Failed")
        print(error)
        return FALLBACK_RESPONSE
    if "confidence_level" in parsed_json:
        parsed_json["confidence_level"] = parsed_json["confidence_level"].lower()
    if "prediction_label" in parsed_json and isinstance(parsed_json["prediction_label"], str):
        label = parsed_json["prediction_label"].strip().lower()
    if label == "fraud":
        parsed_json["prediction_label"] = "Fraud"
    elif label in ["not fraud", "not_fraud"]:
        parsed_json["prediction_label"] = "Not Fraud"

    # Validate JSON Schema
    try:
        validate(
            instance=parsed_json,
            schema=OUTPUT_SCHEMA)
        print("Schema Validation : PASSED")
        return parsed_json
    except ValidationError as error:
        print("\nSchema Validation Failed")
        print(error.message)
        return FALLBACK_RESPONSE

# PII GUARDRAIL
def has_pii(text):
    """
    Detect whether the supplied text contains
    an email address or phone number.
    Returns
    bool
    """
    email_pattern = (r"[a-zA-Z0-9_.+-]+"r"@[a-zA-Z0-9-]+"r"\.[a-zA-Z0-9-.]+")
    phone_pattern = (r"\b\d{10}\b"r"|"r"\b\d{3}[-.\s]\d{3}[-.\s]\d{4}\b")
    return bool(
        re.search(email_pattern, text) 
        or
        re.search(phone_pattern, text))

# SAFE LLM WRAPPER
def safe_call_llm(
        call_function,
        system_prompt,
        user_prompt,
        temperature=0.0,
        max_tokens=512):
    """
    Execute the LLM call only if the user input
    does not contain PII.
    """
    if has_pii(user_prompt):
        print("Input blocked: PII detected.")
        return None
    print("No PII detected.")
    print("Sending request to LLM...")
    response = call_function(
        system_prompt=system_prompt,
        user_prompt=user_prompt,
        temperature=temperature,
        max_tokens=max_tokens)
    return response

# FORMAT USER PROMPT
def create_user_prompt(
        feature_values,
        prediction,
        probability):
    """
    Create the Track C user prompt.
    """
    prompt = USER_PROMPT_TEMPLATE.format(
        feature_values=json.dumps(
            feature_values,
            indent=4,
            default=str),
        prediction=prediction,
        probability=f"{probability:.4f}")
    return prompt

# FUNCTIONS CREATED

print("validate_llm_json()")
print("has_pii()")
print(" safe_call_llm()")
print(" create_user_prompt()")
print("print_divider()")


# TEST INPUT 1 (Contains Email)

blocked_input = """
Customer Name : John Doe
Customer Email : john.doe@gmail.com
Transaction Amount : 1250
"""
print("\nTest Input 1")
print(blocked_input)
if has_pii(blocked_input):
    print("\nResult : BLOCKED")
    print("Reason : Email address detected.")
else:
    print("\nResult : ALLOWED")

# TEST INPUT 2 (No PII)
clean_input = """
Transaction Amount : 1250
Prediction : Fraud
Probability : 0.9721
"""
print("\nTest Input 2")
print(clean_input)
if has_pii(clean_input):
    print("\nResult : BLOCKED")
else:
    print("\nResult : ALLOWED")
    print("Reason : No Personally Identifiable Information found.")

# JSON VALIDATION DEMONSTRATION
sample_json = """
{
    "prediction_label":"Fraud",
    "confidence_level":"high",
    "top_reason":"Large transaction amount",
    "second_reason":"Unusual transaction behaviour",
    "next_step":"Recommend manual verification"
}
"""
print("\nSample LLM Response")
print(sample_json)
validated_json = validate_llm_json(sample_json)
print("\nValidation Result")
print(validated_json)

# TEMPERATURE DEMONSTRATION

print("TEMPERATURE COMPARISON")
print("""
The assignment requires comparing the LLM output using:
Temperature = 0.0
Temperature = 0.7
These comparisons require actual model predictions.
They will be executed in BLOCK 4 after
the prediction pipeline is completed.
""")
print("\nExpected Behaviour")
print("""
Temperature = 0.0
• Deterministic output
• More consistent JSON
• Best for structured extraction
• Recommended for production
Temperature = 0.7
• More creative
• Slight wording variation
• May produce different explanations
• Useful for comparison only
""")
# README REMINDER
print("""
Remember to include:
1. Exact System Prompt
2. User Prompt Template
3. Why temperature = 0
4. JSON Schema
5. Validation Process
6. Temperature Comparison Table
7. Guardrail Test Results
""")

import joblib
import json
import pandas as pd
import numpy as np
from pathlib import Path
print("\nLibraries Imported Successfully")

MODEL_PATH = Path("best_model.pkl")
DATA_PATH = Path("../PART 1/cleaned_data.csv")
if not MODEL_PATH.exists():
    raise FileNotFoundError(
        "best_model.pkl not found. "
        "Copy it from PART 3/output folder into PART 4."
    )
if not DATA_PATH.exists():
    raise FileNotFoundError(
        "cleaned_data.csv not found."
    )
print("\nFiles Found Successfully")
model = joblib.load(MODEL_PATH)
print("\nModel Loaded Successfully")
print(type(model))
df = pd.read_csv(DATA_PATH)
print("\nDataset Loaded")
print("Dataset Shape :", df.shape)
drop_columns = [ "isFraud","TransactionAmt"]
if "TransactionID" in df.columns:
    drop_columns.append(
        "TransactionID"
    )
X = df.drop(
    columns=drop_columns,
    errors="ignore"
)
print("\nFeature Matrix Created")
print("Feature Count :", X.shape[1])

# ENCODE RECORD FUNCTION
def encode_record(features):
    """
    Converts feature dictionary into DataFrame.
    The saved sklearn pipeline already contains:
    - Missing value handling
    - Scaling
    - One hot encoding
    Therefore no manual transformation is required.
    """
    return pd.DataFrame(
        [features]
    )
print("\nencode_record() created")

# CREATE THREE HANDCRAFTED FEATURE VECTORS
sample_1 = X.iloc[0].to_dict()
sample_2 = X.iloc[len(X) // 2].to_dict()
sample_3 = X.iloc[len(X) - 1].to_dict()
test_records = [sample_1,sample_2,sample_3]
print("\nThree Feature Vectors Created")
for index, record in enumerate(test_records, start=1):
    print(f"Sample {index} features:",len(record))

# BLOCK STATUS
print(
"""Completed:
Model Loaded
Dataset Loaded
Feature Matrix Created
encode_record() Created
Three Feature Dictionaries Generated
""")

prediction_results = []
for index, features in enumerate(test_records, start=1):
    print(f"PROCESSING RECORD {index}")
   
    # Convert Dictionary to DataFrame
    encoded_record = encode_record(features)
    # Predict Class
    prediction = model.predict(encoded_record)[0]
    # Predict Probability
    probabilities = model.predict_proba(encoded_record)[0]
    prediction_probability = float(np.max(probabilities))
    # Display Prediction
    print("\nPrediction")
    print("Predicted Class :", prediction)
    print("Probability     :", round(prediction_probability, 4))

    # Convert Numeric Prediction
    if prediction == 1:
        prediction_label = "Fraud"
    else:
        prediction_label = "Not Fraud"

    # Build User Prompt
    user_prompt = create_user_prompt(
        feature_values=features,
        prediction=prediction_label,
        probability=prediction_probability)
    print("\nUser Prompt Created Successfully")

    
    # Call LLM
    llm_response = safe_call_llm(
        call_function=call_llm,
        system_prompt=SYSTEM_PROMPT,
        user_prompt=user_prompt,
        temperature=0.0,
        max_tokens=512)

    # Display Raw Response
    print("\nRaw LLM Response")
    print(llm_response)

    # Store Temporary Result
    prediction_results.append({
        "record_number": index,
        "feature_values": features,
        "prediction": prediction_label,
        "probability": prediction_probability,
        "raw_response": llm_response})
print("JSON VALIDATION AND FINAL RESULTS")
# VALIDATE LLM RESPONSES
final_results = []
for result in prediction_results:
    print(f"VALIDATING RECORD {result['record_number']}")
    raw_response = result["raw_response"]
    validated_json = validate_llm_json(raw_response)
    validation_status = (
        "PASS"
        if validated_json != FALLBACK_RESPONSE
        else "FAIL")
    print("\nValidation Status :", validation_status)

    # Store Final Result
    final_results.append({
        "record_number": result["record_number"],
        "feature_values": result["feature_values"],
        "prediction": result["prediction"],
        "probability": result["probability"],
        "llm_output": validated_json,
        "validation_status": validation_status})

# DISPLAY FINAL RESULTS

print("RESULTS")
for result in final_results:
    print("\n")
    print(f"RECORD {result['record_number']}")
    print("\nPrediction")
    print(result["prediction"])
    print("\nProbability")
    print(round(result["probability"], 4))
    print("\nValidated JSON")
    print(
        json.dumps(
            result["llm_output"],
            indent=4))
    print("\nValidation")
    print(result["validation_status"])

# CREATE README TABLE DATA
readme_rows = []
for result in final_results:
    readme_rows.append({
        "Feature Input":f"Record {result['record_number']}",
        "Predicted Class":result["prediction"],
        "Probability":round(result["probability"], 4),
        "Explanation JSON":json.dumps(result["llm_output"]),
        "Validation Status":result["validation_status"]})
readme_table = pd.DataFrame(readme_rows)
print("README TABLE")
print(readme_table)

# SAVE
OUTPUT_DIR = Path("outputs")
OUTPUT_DIR.mkdir(exist_ok=True)
readme_table.to_csv(OUTPUT_DIR / "track_c_results.csv",index=False)
print("\nResults saved to:")
print(OUTPUT_DIR / "track_c_results.csv")
print("""
Completed:
Loaded best_model.pkl
encode_record()
Three feature vectors
predict()
predict_proba()
Built structured prompt
LLM called
Raw response captured
JSON parsed
Schema validated
Validation status reported
README table generated
""")

import time
print("\nWaiting 60 seconds to avoid Gemini rate limit...")
time.sleep(60)

print("TEMPERATURE COMPARISON")
temperature_results = []
# PROCESS ALL THREE RECORDS
for index, features in enumerate(test_records, start=1):
    print("\n")
    print(f"RECORD {index}")

    # Encode Record
    encoded_record = encode_record(features)
    # Prediction
    prediction = model.predict(encoded_record)[0]
    probability = float(np.max( model.predict_proba(encoded_record) ))
    if prediction == 1:
        prediction_label = "Fraud"
    else:
        prediction_label = "Not Fraud"

    # Create Prompt
    user_prompt = create_user_prompt(
        feature_values=features,
        prediction=prediction_label,
        probability=probability)

    # Temperature = 0
    print("\nTemperature = 0.0")
    response_temp0 = safe_call_llm(
        call_function=call_llm,
        system_prompt=SYSTEM_PROMPT,
        user_prompt=user_prompt,
        temperature=0.0,
        max_tokens=512)
    validated_temp0 = validate_llm_json(
        response_temp0)

    # Temperature = 0.7
    print("\nTemperature = 0.7")
    response_temp07 = safe_call_llm(
        call_function=call_llm,
        system_prompt=SYSTEM_PROMPT,
        user_prompt=user_prompt,
        temperature=0.7,
        max_tokens=512)
    validated_temp07 = validate_llm_json(
        response_temp07)

    # Display Results
    print("\nOutput @ Temperature = 0.0")
    print(
        json.dumps(
            validated_temp0,
            indent=4))
    print("\nOutput @ Temperature = 0.7")
    print(
        json.dumps(
            validated_temp07,
            indent=4))

    # Save Results
    temperature_results.append({
        "Input":
            f"Record {index}",
        "Prediction":prediction_label,
        "Probability":round(probability, 4),
        "Temp0":validated_temp0,
        "Temp07":validated_temp07 })
print("TEMPERATURE COMPARISON COMPLETED")



# TEMPERATURE COMPARISON TABLE
comparison_rows = []
for item in temperature_results:
    temp0_text = json.dumps(item["Temp0"])
    temp07_text = json.dumps(item["Temp07"])
    if temp0_text == temp07_text:
        difference = "No noticeable difference"
    else:
        difference = "Response wording changed"
    comparison_rows.append({
        "Input":item["Input"],
        "Output @ Temp=0":temp0_text,
        "Output @ Temp=0.7":temp07_text,
        "Key Difference": difference })
temperature_table = pd.DataFrame(comparison_rows)
print("\nTemperature Comparison Table\n")
print(temperature_table)

# GUARDRAIL SUMMARY
print("GUARDRAIL ")
guardrail_rows = [{
    "Input":"Contains Email",
    "Guardrail":"BLOCKED"},
    {"Input":"No Email",
     "Guardrail":"ALLOWED"}]
guardrail_table = pd.DataFrame(guardrail_rows)
print(guardrail_table)

# FINAL DEMONSTRATION TABLE
demo_rows = []
for result in final_results:
    demo_rows.append({
        "Input":f"Record {result['record_number']}",
        "LLM Output":json.dumps(result["llm_output"]),
        "Valid JSON":result["validation_status"],
        "Pass / Block":"PASS" })
demo_table = pd.DataFrame(demo_rows)
print("TABLE")
print(demo_table)

# SAVE RESULTS
temperature_table.to_csv( OUTPUT_DIR / "temperature_comparison.csv",index=False)
guardrail_table.to_csv(OUTPUT_DIR / "guardrail_results.csv",index=False)
demo_table.to_csv(OUTPUT_DIR / "demo_results.csv",index=False)

# FINAL SUMMARY
print("""
Track Selected : Track C
Model Prediction Explanation Pipeline
Completed
 Environment Variable API Key
 call_llm()
 API Test
 Zero-shot Prompt
 JSON Schema
 JSON Validation
 ValidationError Handling
 JSONDecodeError Handling
 Fallback Response
 PII Guardrail
 Three Feature Inputs
 encode_record()
 predict()
 predict_proba()
 LLM Explanation
 Temperature = 0
 Temperature = 0.7
 Temperature Comparison
 Guardrail Demonstration
 README Tables
 CSV Results Saved
""")

# GENERATED FILES

print("\nGenerated Files\n")

files = [
    "track_c_results.csv",
    "temperature_comparison.csv",
    "guardrail_results.csv",
    "demo_results.csv"
]
for file in files:
    print(file)
